import '../styles/globals.css'
import Layout from '../components/layout'
import Head from 'next/head'
import "swiper/css/bundle";

function MyApp({ Component, pageProps }) {
  return (
    <Layout>
        <Head>
        <title>Food Make</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://img.icons8.com/external-becris-lineal-becris/344/external-cooking-coping-skills-becris-lineal-becris.png" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"></link>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300&display=swap" rel="stylesheet"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Yuji+Mai&display=swap" rel="stylesheet"/>
      </Head>
      <Component {...pageProps} />
    </Layout>
  )
}

export default MyApp
